In [ ]:
import pandas as pd
import pixiedust

df = pd.read_csv(
    "speedtest.log",
    names=[
        "server_id",
        "sponsor",
        "server_name",
        "timestamp",
        "distance",
        "ping",
        "download",
        "upload",
        "share",
        "ip_address"
    ],
    usecols=["timestamp", "ping", "download", "upload"],
    parse_dates=["timestamp"]
)

display(df)